spring.application.name=app
server.port=3000

spring.security.user.name=admin
spring.security.user.password=admin123

logging.level.org.springframework.jdbc.core=DEBUG

spring.datasource.url=jdbc:postgresql://roger-postgres-db.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=dev
spring.datasource.password=Test12345!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true